/* tslint:disable */
/* eslint-disable */
/**
 * AulaViva API
 * API principal de AulaViva, plataforma SaaS multi-tenant para gestión de evaluaciones, progreso académico y Tutor IA. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Answer
 */
export interface Answer {
    /**
     * 
     */
    questionId: string;
    /**
     * 
     */
    selectedOption: number;
}

/**
 * Check if a given object implements the Answer interface.
 */
export function instanceOfAnswer(value: object): value is Answer {
    if (!('questionId' in value) || value['questionId'] === undefined) return false;
    if (!('selectedOption' in value) || value['selectedOption'] === undefined) return false;
    return true;
}

export function AnswerFromJSON(json: any): Answer {
    return AnswerFromJSONTyped(json, false);
}

export function AnswerFromJSONTyped(json: any, ignoreDiscriminator: boolean): Answer {
    if (json == null) {
        return json;
    }
    return {
        
        'questionId': json['questionId'],
        'selectedOption': json['selectedOption'],
    };
}

export function AnswerToJSON(json: any): Answer {
    return AnswerToJSONTyped(json, false);
}

export function AnswerToJSONTyped(value?: Answer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'questionId': value['questionId'],
        'selectedOption': value['selectedOption'],
    };
}

