/* tslint:disable */
/* eslint-disable */
/**
 * AulaViva API
 * API principal de AulaViva, plataforma SaaS multi-tenant para gestión de evaluaciones, progreso académico y Tutor IA. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QuestionInput } from './QuestionInput';
import {
    QuestionInputFromJSON,
    QuestionInputFromJSONTyped,
    QuestionInputToJSON,
    QuestionInputToJSONTyped,
} from './QuestionInput';

/**
 * 
 * @export
 * @interface CreateEvaluationRequest
 */
export interface CreateEvaluationRequest {
    /**
     * Identificador del curso
     */
    courseId: string;
    /**
     * Título de la evaluación
     */
    title: string;
    /**
     * 
     */
    questions: Array<QuestionInput>;
}

/**
 * Check if a given object implements the CreateEvaluationRequest interface.
 */
export function instanceOfCreateEvaluationRequest(value: object): value is CreateEvaluationRequest {
    if (!('courseId' in value) || value['courseId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('questions' in value) || value['questions'] === undefined) return false;
    return true;
}

export function CreateEvaluationRequestFromJSON(json: any): CreateEvaluationRequest {
    return CreateEvaluationRequestFromJSONTyped(json, false);
}

export function CreateEvaluationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEvaluationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'courseId': json['courseId'],
        'title': json['title'],
        'questions': ((json['questions'] as Array<any>).map(QuestionInputFromJSON)),
    };
}

export function CreateEvaluationRequestToJSON(json: any): CreateEvaluationRequest {
    return CreateEvaluationRequestToJSONTyped(json, false);
}

export function CreateEvaluationRequestToJSONTyped(value?: CreateEvaluationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'courseId': value['courseId'],
        'title': value['title'],
        'questions': ((value['questions'] as Array<any>).map(QuestionInputToJSON)),
    };
}

