/* tslint:disable */
/* eslint-disable */
/**
 * AulaViva API
 * API principal de AulaViva, plataforma SaaS multi-tenant para gestión de evaluaciones, progreso académico y Tutor IA. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QuestionResponse } from './QuestionResponse';
import {
    QuestionResponseFromJSON,
    QuestionResponseFromJSONTyped,
    QuestionResponseToJSON,
    QuestionResponseToJSONTyped,
} from './QuestionResponse';

/**
 * 
 * @export
 * @interface EvaluationResponse
 */
export interface EvaluationResponse {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    title: string;
    /**
     * 
     */
    questions: Array<QuestionResponse>;
}

/**
 * Check if a given object implements the EvaluationResponse interface.
 */
export function instanceOfEvaluationResponse(value: object): value is EvaluationResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('questions' in value) || value['questions'] === undefined) return false;
    return true;
}

export function EvaluationResponseFromJSON(json: any): EvaluationResponse {
    return EvaluationResponseFromJSONTyped(json, false);
}

export function EvaluationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvaluationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'questions': ((json['questions'] as Array<any>).map(QuestionResponseFromJSON)),
    };
}

export function EvaluationResponseToJSON(json: any): EvaluationResponse {
    return EvaluationResponseToJSONTyped(json, false);
}

export function EvaluationResponseToJSONTyped(value?: EvaluationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'questions': ((value['questions'] as Array<any>).map(QuestionResponseToJSON)),
    };
}

