/* tslint:disable */
/* eslint-disable */
/**
 * AulaViva API
 * API principal de AulaViva, plataforma SaaS multi-tenant para gestión de evaluaciones, progreso académico y Tutor IA. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EvaluationCompletedEvent
 */
export interface EvaluationCompletedEvent {
    /**
     * Identificador de la evaluación.
     */
    evaluationId: string;
    /**
     * Identificador del estudiante.
     */
    studentId: string;
    /**
     * Nota obtenida por el estudiante.
     */
    grade: number;
}

/**
 * Check if a given object implements the EvaluationCompletedEvent interface.
 */
export function instanceOfEvaluationCompletedEvent(value: object): value is EvaluationCompletedEvent {
    if (!('evaluationId' in value) || value['evaluationId'] === undefined) return false;
    if (!('studentId' in value) || value['studentId'] === undefined) return false;
    if (!('grade' in value) || value['grade'] === undefined) return false;
    return true;
}

export function EvaluationCompletedEventFromJSON(json: any): EvaluationCompletedEvent {
    return EvaluationCompletedEventFromJSONTyped(json, false);
}

export function EvaluationCompletedEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvaluationCompletedEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'evaluationId': json['evaluationId'],
        'studentId': json['studentId'],
        'grade': json['grade'],
    };
}

export function EvaluationCompletedEventToJSON(json: any): EvaluationCompletedEvent {
    return EvaluationCompletedEventToJSONTyped(json, false);
}

export function EvaluationCompletedEventToJSONTyped(value?: EvaluationCompletedEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'evaluationId': value['evaluationId'],
        'studentId': value['studentId'],
        'grade': value['grade'],
    };
}

