/* tslint:disable */
/* eslint-disable */
/**
 * AulaViva API
 * API principal de AulaViva, plataforma SaaS multi-tenant para gestión de evaluaciones, progreso académico y Tutor IA. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EvaluationCreatedResponse
 */
export interface EvaluationCreatedResponse {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    title: string;
    /**
     * 
     */
    status: EvaluationCreatedResponseStatusEnum;
}


/**
 * @export
 */
export const EvaluationCreatedResponseStatusEnum = {
    Created: 'CREATED',
} as const;
export type EvaluationCreatedResponseStatusEnum = typeof EvaluationCreatedResponseStatusEnum[keyof typeof EvaluationCreatedResponseStatusEnum];


/**
 * Check if a given object implements the EvaluationCreatedResponse interface.
 */
export function instanceOfEvaluationCreatedResponse(value: object): value is EvaluationCreatedResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (value['status'] !== 'CREATED') return false;
    
    return true;
}

export function EvaluationCreatedResponseFromJSON(json: any): EvaluationCreatedResponse {
    return EvaluationCreatedResponseFromJSONTyped(json, false);
}

export function EvaluationCreatedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EvaluationCreatedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'status': json['status'],
    };
}

export function EvaluationCreatedResponseToJSON(json: any): EvaluationCreatedResponse {
    return EvaluationCreatedResponseToJSONTyped(json, false);
}

export function EvaluationCreatedResponseToJSONTyped(value?: EvaluationCreatedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'status': value['status'],
    };
}

