/* tslint:disable */
/* eslint-disable */
/**
 * AulaViva API
 * API principal de AulaViva, plataforma SaaS multi-tenant para gestión de evaluaciones, progreso académico y Tutor IA. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProblemDetailsErrorsInner } from './ProblemDetailsErrorsInner';
import {
    ProblemDetailsErrorsInnerFromJSON,
    ProblemDetailsErrorsInnerFromJSONTyped,
    ProblemDetailsErrorsInnerToJSON,
    ProblemDetailsErrorsInnerToJSONTyped,
} from './ProblemDetailsErrorsInner';

/**
 * Formato estándar de error basado en RFC 7807.
 * @export
 * @interface ProblemDetails
 */
export interface ProblemDetails {
    /**
     * URI que identifica el tipo de problema.
     */
    type: string;
    /**
     * Resumen breve del problema.
     */
    title: string;
    /**
     * Código de estado HTTP.
     */
    status: number;
    /**
     * Explicación específica del problema.
     */
    detail: string;
    /**
     * URI que identifica la ocurrencia específica del problema.
     */
    instance: string;
    /**
     * Identificador de correlación para trazabilidad.
     */
    traceId?: string;
    /**
     * Lista detallada de errores de validación, cuando corresponda.
     */
    errors?: Array<ProblemDetailsErrorsInner>;
}

/**
 * Check if a given object implements the ProblemDetails interface.
 */
export function instanceOfProblemDetails(value: object): value is ProblemDetails {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('detail' in value) || value['detail'] === undefined) return false;
    if (!('instance' in value) || value['instance'] === undefined) return false;
    return true;
}

export function ProblemDetailsFromJSON(json: any): ProblemDetails {
    return ProblemDetailsFromJSONTyped(json, false);
}

export function ProblemDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProblemDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'title': json['title'],
        'status': json['status'],
        'detail': json['detail'],
        'instance': json['instance'],
        'traceId': json['trace_id'] == null ? undefined : json['trace_id'],
        'errors': json['errors'] == null ? undefined : ((json['errors'] as Array<any>).map(ProblemDetailsErrorsInnerFromJSON)),
    };
}

export function ProblemDetailsToJSON(json: any): ProblemDetails {
    return ProblemDetailsToJSONTyped(json, false);
}

export function ProblemDetailsToJSONTyped(value?: ProblemDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'title': value['title'],
        'status': value['status'],
        'detail': value['detail'],
        'instance': value['instance'],
        'trace_id': value['traceId'],
        'errors': value['errors'] == null ? undefined : ((value['errors'] as Array<any>).map(ProblemDetailsErrorsInnerToJSON)),
    };
}

