/* tslint:disable */
/* eslint-disable */
/**
 * AulaViva API
 * API principal de AulaViva, plataforma SaaS multi-tenant para gestión de evaluaciones, progreso académico y Tutor IA. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProblemDetailsErrorsInner
 */
export interface ProblemDetailsErrorsInner {
    /**
     * 
     */
    field: string;
    /**
     * 
     */
    message: string;
}

/**
 * Check if a given object implements the ProblemDetailsErrorsInner interface.
 */
export function instanceOfProblemDetailsErrorsInner(value: object): value is ProblemDetailsErrorsInner {
    if (!('field' in value) || value['field'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ProblemDetailsErrorsInnerFromJSON(json: any): ProblemDetailsErrorsInner {
    return ProblemDetailsErrorsInnerFromJSONTyped(json, false);
}

export function ProblemDetailsErrorsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProblemDetailsErrorsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'field': json['field'],
        'message': json['message'],
    };
}

export function ProblemDetailsErrorsInnerToJSON(json: any): ProblemDetailsErrorsInner {
    return ProblemDetailsErrorsInnerToJSONTyped(json, false);
}

export function ProblemDetailsErrorsInnerToJSONTyped(value?: ProblemDetailsErrorsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'field': value['field'],
        'message': value['message'],
    };
}

