/* tslint:disable */
/* eslint-disable */
/**
 * AulaViva API
 * API principal de AulaViva, plataforma SaaS multi-tenant para gestión de evaluaciones, progreso académico y Tutor IA. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QuestionResponse
 */
export interface QuestionResponse {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    text: string;
    /**
     * 
     */
    options: Array<string>;
    /**
     * Puntaje asignado a la pregunta
     */
    points: number;
}

/**
 * Check if a given object implements the QuestionResponse interface.
 */
export function instanceOfQuestionResponse(value: object): value is QuestionResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('options' in value) || value['options'] === undefined) return false;
    if (!('points' in value) || value['points'] === undefined) return false;
    return true;
}

export function QuestionResponseFromJSON(json: any): QuestionResponse {
    return QuestionResponseFromJSONTyped(json, false);
}

export function QuestionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuestionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'text': json['text'],
        'options': json['options'],
        'points': json['points'],
    };
}

export function QuestionResponseToJSON(json: any): QuestionResponse {
    return QuestionResponseToJSONTyped(json, false);
}

export function QuestionResponseToJSONTyped(value?: QuestionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'text': value['text'],
        'options': value['options'],
        'points': value['points'],
    };
}

