/* tslint:disable */
/* eslint-disable */
/**
 * AulaViva API
 * API principal de AulaViva, plataforma SaaS multi-tenant para gestión de evaluaciones, progreso académico y Tutor IA. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QuestionInput
 */
export interface QuestionInput {
    /**
     * Enunciado de la pregunta
     */
    text: string;
    /**
     * 
     */
    options: Array<string>;
    /**
     * Índice de la alternativa correcta
     */
    correctOption: number;
    /**
     * 
     */
    points: number;
}

/**
 * Check if a given object implements the QuestionInput interface.
 */
export function instanceOfQuestionInput(value: object): value is QuestionInput {
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('options' in value) || value['options'] === undefined) return false;
    if (!('correctOption' in value) || value['correctOption'] === undefined) return false;
    if (!('points' in value) || value['points'] === undefined) return false;
    return true;
}

export function QuestionInputFromJSON(json: any): QuestionInput {
    return QuestionInputFromJSONTyped(json, false);
}

export function QuestionInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuestionInput {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'],
        'options': json['options'],
        'correctOption': json['correctOption'],
        'points': json['points'],
    };
}

export function QuestionInputToJSON(json: any): QuestionInput {
    return QuestionInputToJSONTyped(json, false);
}

export function QuestionInputToJSONTyped(value?: QuestionInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
        'options': value['options'],
        'correctOption': value['correctOption'],
        'points': value['points'],
    };
}

