/* tslint:disable */
/* eslint-disable */
/**
 * AulaViva API
 * API principal de AulaViva, plataforma SaaS multi-tenant para gestión de evaluaciones, progreso académico y Tutor IA. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StudentProgressResponse
 */
export interface StudentProgressResponse {
    /**
     * 
     */
    completedEvaluations: number;
    /**
     * 
     */
    pendingEvaluations: number;
    /**
     * 
     */
    averageGrade: number;
}

/**
 * Check if a given object implements the StudentProgressResponse interface.
 */
export function instanceOfStudentProgressResponse(value: object): value is StudentProgressResponse {
    if (!('completedEvaluations' in value) || value['completedEvaluations'] === undefined) return false;
    if (!('pendingEvaluations' in value) || value['pendingEvaluations'] === undefined) return false;
    if (!('averageGrade' in value) || value['averageGrade'] === undefined) return false;
    return true;
}

export function StudentProgressResponseFromJSON(json: any): StudentProgressResponse {
    return StudentProgressResponseFromJSONTyped(json, false);
}

export function StudentProgressResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudentProgressResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'completedEvaluations': json['completedEvaluations'],
        'pendingEvaluations': json['pendingEvaluations'],
        'averageGrade': json['averageGrade'],
    };
}

export function StudentProgressResponseToJSON(json: any): StudentProgressResponse {
    return StudentProgressResponseToJSONTyped(json, false);
}

export function StudentProgressResponseToJSONTyped(value?: StudentProgressResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'completedEvaluations': value['completedEvaluations'],
        'pendingEvaluations': value['pendingEvaluations'],
        'averageGrade': value['averageGrade'],
    };
}

