/* tslint:disable */
/* eslint-disable */
/**
 * AulaViva API
 * API principal de AulaViva, plataforma SaaS multi-tenant para gestión de evaluaciones, progreso académico y Tutor IA. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Answer } from './Answer';
import {
    AnswerFromJSON,
    AnswerFromJSONTyped,
    AnswerToJSON,
    AnswerToJSONTyped,
} from './Answer';

/**
 * 
 * @export
 * @interface SubmissionRequest
 */
export interface SubmissionRequest {
    /**
     * 
     */
    answers: Array<Answer>;
}

/**
 * Check if a given object implements the SubmissionRequest interface.
 */
export function instanceOfSubmissionRequest(value: object): value is SubmissionRequest {
    if (!('answers' in value) || value['answers'] === undefined) return false;
    return true;
}

export function SubmissionRequestFromJSON(json: any): SubmissionRequest {
    return SubmissionRequestFromJSONTyped(json, false);
}

export function SubmissionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmissionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'answers': ((json['answers'] as Array<any>).map(AnswerFromJSON)),
    };
}

export function SubmissionRequestToJSON(json: any): SubmissionRequest {
    return SubmissionRequestToJSONTyped(json, false);
}

export function SubmissionRequestToJSONTyped(value?: SubmissionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'answers': ((value['answers'] as Array<any>).map(AnswerToJSON)),
    };
}

