/* tslint:disable */
/* eslint-disable */
/**
 * AulaViva API
 * API principal de AulaViva, plataforma SaaS multi-tenant para gestión de evaluaciones, progreso académico y Tutor IA. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Resultado de la corrección automática de una evaluación.
 * @export
 * @interface SubmissionResponse
 */
export interface SubmissionResponse {
    /**
     * 
     */
    grade: number;
    /**
     * Puntaje obtenido por el estudiante.
     */
    score: number;
    /**
     * Puntaje máximo posible de la evaluación.
     */
    maxScore: number;
    /**
     * 
     */
    status: SubmissionResponseStatusEnum;
}


/**
 * @export
 */
export const SubmissionResponseStatusEnum = {
    Completed: 'COMPLETED',
} as const;
export type SubmissionResponseStatusEnum = typeof SubmissionResponseStatusEnum[keyof typeof SubmissionResponseStatusEnum];


/**
 * Check if a given object implements the SubmissionResponse interface.
 */
export function instanceOfSubmissionResponse(value: object): value is SubmissionResponse {
    if (!('grade' in value) || value['grade'] === undefined) return false;
    if (!('score' in value) || value['score'] === undefined) return false;
    if (!('maxScore' in value) || value['maxScore'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (value['status'] !== 'COMPLETED') return false;
    
    return true;
}

export function SubmissionResponseFromJSON(json: any): SubmissionResponse {
    return SubmissionResponseFromJSONTyped(json, false);
}

export function SubmissionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmissionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'grade': json['grade'],
        'score': json['score'],
        'maxScore': json['maxScore'],
        'status': json['status'],
    };
}

export function SubmissionResponseToJSON(json: any): SubmissionResponse {
    return SubmissionResponseToJSONTyped(json, false);
}

export function SubmissionResponseToJSONTyped(value?: SubmissionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'grade': value['grade'],
        'score': value['score'],
        'maxScore': value['maxScore'],
        'status': value['status'],
    };
}

