/* tslint:disable */
/* eslint-disable */
/**
 * AulaViva API
 * API principal de AulaViva, plataforma SaaS multi-tenant para gestión de evaluaciones, progreso académico y Tutor IA. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TutorQuestionResponse
 */
export interface TutorQuestionResponse {
    /**
     * Respuesta generada por el Tutor IA
     */
    answer: string;
    /**
     * Fuentes utilizadas por el RAG
     */
    sources?: Array<string>;
}

/**
 * Check if a given object implements the TutorQuestionResponse interface.
 */
export function instanceOfTutorQuestionResponse(value: object): value is TutorQuestionResponse {
    if (!('answer' in value) || value['answer'] === undefined) return false;
    return true;
}

export function TutorQuestionResponseFromJSON(json: any): TutorQuestionResponse {
    return TutorQuestionResponseFromJSONTyped(json, false);
}

export function TutorQuestionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TutorQuestionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'answer': json['answer'],
        'sources': json['sources'] == null ? undefined : json['sources'],
    };
}

export function TutorQuestionResponseToJSON(json: any): TutorQuestionResponse {
    return TutorQuestionResponseToJSONTyped(json, false);
}

export function TutorQuestionResponseToJSONTyped(value?: TutorQuestionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'answer': value['answer'],
        'sources': value['sources'],
    };
}

