/* tslint:disable */
/* eslint-disable */
/**
 * AulaViva API
 * API principal de AulaViva, plataforma SaaS multi-tenant para gestión de evaluaciones, progreso académico y Tutor IA. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TutorQuestionRequest
 */
export interface TutorQuestionRequest {
    /**
     * Curso sobre el cual se realiza la consulta
     */
    courseId: string;
    /**
     * Pregunta académica realizada por el estudiante
     */
    question: string;
}

/**
 * Check if a given object implements the TutorQuestionRequest interface.
 */
export function instanceOfTutorQuestionRequest(value: object): value is TutorQuestionRequest {
    if (!('courseId' in value) || value['courseId'] === undefined) return false;
    if (!('question' in value) || value['question'] === undefined) return false;
    return true;
}

export function TutorQuestionRequestFromJSON(json: any): TutorQuestionRequest {
    return TutorQuestionRequestFromJSONTyped(json, false);
}

export function TutorQuestionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TutorQuestionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'courseId': json['courseId'],
        'question': json['question'],
    };
}

export function TutorQuestionRequestToJSON(json: any): TutorQuestionRequest {
    return TutorQuestionRequestToJSONTyped(json, false);
}

export function TutorQuestionRequestToJSONTyped(value?: TutorQuestionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'courseId': value['courseId'],
        'question': value['question'],
    };
}

