/* tslint:disable */
/* eslint-disable */
/**
 * AulaViva API
 * API principal de AulaViva, plataforma SaaS multi-tenant para gestión de evaluaciones, progreso académico y Tutor IA. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ,
    FromJSON,
    ToJSON,
} from '../models/';

export interface EvaluationCompletedPostRequest {
    /**
     * 
     */
    evaluationCompletedEvent: EvaluationCompletedEvent;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Creates request options for evaluationCompletedPost without sending the request
     */
    async evaluationCompletedPostRequestOpts(requestParameters: EvaluationCompletedPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['evaluationCompletedEvent'] == null) {
            throw new runtime.RequiredError(
                'evaluationCompletedEvent',
                'Required parameter "evaluationCompletedEvent" was null or undefined when calling evaluationCompletedPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/evaluationCompleted`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EvaluationCompletedEventToJSON(requestParameters['evaluationCompletedEvent']),
        };
    }

    /**
     * Notifica al consumidor cuando un estudiante completa una evaluación y se obtiene su nota. 
     * Notificación de evaluación completada
     */
    async evaluationCompletedPostRaw(requestParameters: EvaluationCompletedPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.evaluationCompletedPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Notifica al consumidor cuando un estudiante completa una evaluación y se obtiene su nota. 
     * Notificación de evaluación completada
     */
    async evaluationCompletedPost(requestParameters: EvaluationCompletedPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.evaluationCompletedPostRaw(requestParameters, initOverrides);
    }

}
