/* tslint:disable */
/* eslint-disable */
/**
 * AulaViva API
 * API principal de AulaViva, plataforma SaaS multi-tenant para gestión de evaluaciones, progreso académico y Tutor IA. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateEvaluationRequest,
    CreateEvaluationRequestFromJSON,
    CreateEvaluationRequestToJSON,
} from '../models/CreateEvaluationRequest';
import {
    type EvaluationCreatedResponse,
    EvaluationCreatedResponseFromJSON,
    EvaluationCreatedResponseToJSON,
} from '../models/EvaluationCreatedResponse';
import {
    type EvaluationResponse,
    EvaluationResponseFromJSON,
    EvaluationResponseToJSON,
} from '../models/EvaluationResponse';
import {
    type ProblemDetails,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
} from '../models/ProblemDetails';
import {
    type SubmissionRequest,
    SubmissionRequestFromJSON,
    SubmissionRequestToJSON,
} from '../models/SubmissionRequest';
import {
    type SubmissionResponse,
    SubmissionResponseFromJSON,
    SubmissionResponseToJSON,
} from '../models/SubmissionResponse';

export interface CreateEvaluationOperationRequest {
    /**
     * Clave única utilizada para garantizar la idempotencia de la operación.
     * 
     */
    idempotencyKey: string;
    /**
     * 
     */
    createEvaluationRequest: CreateEvaluationRequest;
}

export interface GetEvaluationRequest {
    /**
     * Identificador de la evaluación
     */
    evaluationId: string;
}

export interface SubmitEvaluationRequest {
    /**
     * Identificador de la evaluación
     */
    evaluationId: string;
    /**
     * Clave única utilizada para garantizar la idempotencia de la operación.
     * 
     */
    idempotencyKey: string;
    /**
     * 
     */
    submissionRequest: SubmissionRequest;
}

/**
 * 
 */
export class EvaluationsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createEvaluation without sending the request
     */
    async createEvaluationRequestOpts(requestParameters: CreateEvaluationOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling createEvaluation().'
            );
        }

        if (requestParameters['createEvaluationRequest'] == null) {
            throw new runtime.RequiredError(
                'createEvaluationRequest',
                'Required parameter "createEvaluationRequest" was null or undefined when calling createEvaluation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/evaluations`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateEvaluationRequestToJSON(requestParameters['createEvaluationRequest']),
        };
    }

    /**
     * Permite a un profesor crear una evaluación para un curso.
     * Crear una evaluación
     */
    async createEvaluationRaw(requestParameters: CreateEvaluationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EvaluationCreatedResponse>> {
        const requestOptions = await this.createEvaluationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EvaluationCreatedResponseFromJSON(jsonValue));
    }

    /**
     * Permite a un profesor crear una evaluación para un curso.
     * Crear una evaluación
     */
    async createEvaluation(requestParameters: CreateEvaluationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EvaluationCreatedResponse> {
        const response = await this.createEvaluationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getEvaluation without sending the request
     */
    async getEvaluationRequestOpts(requestParameters: GetEvaluationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['evaluationId'] == null) {
            throw new runtime.RequiredError(
                'evaluationId',
                'Required parameter "evaluationId" was null or undefined when calling getEvaluation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/evaluations/{evaluationId}`;
        urlPath = urlPath.replace('{evaluationId}', encodeURIComponent(String(requestParameters['evaluationId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Permite a un estudiante consultar una evaluación. Las respuestas correctas no son incluidas en la respuesta. 
     * Consultar una evaluación
     */
    async getEvaluationRaw(requestParameters: GetEvaluationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EvaluationResponse>> {
        const requestOptions = await this.getEvaluationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EvaluationResponseFromJSON(jsonValue));
    }

    /**
     * Permite a un estudiante consultar una evaluación. Las respuestas correctas no son incluidas en la respuesta. 
     * Consultar una evaluación
     */
    async getEvaluation(requestParameters: GetEvaluationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EvaluationResponse> {
        const response = await this.getEvaluationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for submitEvaluation without sending the request
     */
    async submitEvaluationRequestOpts(requestParameters: SubmitEvaluationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['evaluationId'] == null) {
            throw new runtime.RequiredError(
                'evaluationId',
                'Required parameter "evaluationId" was null or undefined when calling submitEvaluation().'
            );
        }

        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling submitEvaluation().'
            );
        }

        if (requestParameters['submissionRequest'] == null) {
            throw new runtime.RequiredError(
                'submissionRequest',
                'Required parameter "submissionRequest" was null or undefined when calling submitEvaluation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/evaluations/{evaluationId}/submissions`;
        urlPath = urlPath.replace('{evaluationId}', encodeURIComponent(String(requestParameters['evaluationId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SubmissionRequestToJSON(requestParameters['submissionRequest']),
        };
    }

    /**
     * Permite a un estudiante enviar sus respuestas para realizar la corrección automática. 
     * Enviar respuestas de una evaluación
     */
    async submitEvaluationRaw(requestParameters: SubmitEvaluationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubmissionResponse>> {
        const requestOptions = await this.submitEvaluationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SubmissionResponseFromJSON(jsonValue));
    }

    /**
     * Permite a un estudiante enviar sus respuestas para realizar la corrección automática. 
     * Enviar respuestas de una evaluación
     */
    async submitEvaluation(requestParameters: SubmitEvaluationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubmissionResponse> {
        const response = await this.submitEvaluationRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
