/* tslint:disable */
/* eslint-disable */
/**
 * AulaViva API
 * API principal de AulaViva, plataforma SaaS multi-tenant para gestión de evaluaciones, progreso académico y Tutor IA. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ProblemDetails,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
} from '../models/ProblemDetails';
import {
    type StudentProgressResponse,
    StudentProgressResponseFromJSON,
    StudentProgressResponseToJSON,
} from '../models/StudentProgressResponse';

export interface GetStudentProgressRequest {
    /**
     * Identificador del estudiante
     */
    studentId: string;
}

/**
 * 
 */
export class ProgressApi extends runtime.BaseAPI {

    /**
     * Creates request options for getStudentProgress without sending the request
     */
    async getStudentProgressRequestOpts(requestParameters: GetStudentProgressRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['studentId'] == null) {
            throw new runtime.RequiredError(
                'studentId',
                'Required parameter "studentId" was null or undefined when calling getStudentProgress().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/students/{studentId}/progress`;
        urlPath = urlPath.replace('{studentId}', encodeURIComponent(String(requestParameters['studentId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Permite a un profesor o apoderado consultar el progreso académico de un estudiante. 
     * Consultar progreso de un estudiante
     */
    async getStudentProgressRaw(requestParameters: GetStudentProgressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StudentProgressResponse>> {
        const requestOptions = await this.getStudentProgressRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StudentProgressResponseFromJSON(jsonValue));
    }

    /**
     * Permite a un profesor o apoderado consultar el progreso académico de un estudiante. 
     * Consultar progreso de un estudiante
     */
    async getStudentProgress(requestParameters: GetStudentProgressRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StudentProgressResponse> {
        const response = await this.getStudentProgressRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
