/* tslint:disable */
/* eslint-disable */
/**
 * AulaViva API
 * API principal de AulaViva, plataforma SaaS multi-tenant para gestión de evaluaciones, progreso académico y Tutor IA. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ProblemDetails,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
} from '../models/ProblemDetails';
import {
    type TutorQuestionRequest,
    TutorQuestionRequestFromJSON,
    TutorQuestionRequestToJSON,
} from '../models/TutorQuestionRequest';
import {
    type TutorQuestionResponse,
    TutorQuestionResponseFromJSON,
    TutorQuestionResponseToJSON,
} from '../models/TutorQuestionResponse';

export interface AskTutorRequest {
    /**
     * Clave única utilizada para garantizar la idempotencia de la operación.
     * 
     */
    idempotencyKey: string;
    /**
     * 
     */
    tutorQuestionRequest: TutorQuestionRequest;
}

/**
 * 
 */
export class TutorIAApi extends runtime.BaseAPI {

    /**
     * Creates request options for askTutor without sending the request
     */
    async askTutorRequestOpts(requestParameters: AskTutorRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling askTutor().'
            );
        }

        if (requestParameters['tutorQuestionRequest'] == null) {
            throw new runtime.RequiredError(
                'tutorQuestionRequest',
                'Required parameter "tutorQuestionRequest" was null or undefined when calling askTutor().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/tutor/questions`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TutorQuestionRequestToJSON(requestParameters['tutorQuestionRequest']),
        };
    }

    /**
     * Permite a un estudiante realizar una consulta académica. El Tutor IA genera una respuesta utilizando información contextual recuperada mediante RAG. 
     * Realizar una consulta al Tutor IA
     */
    async askTutorRaw(requestParameters: AskTutorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TutorQuestionResponse>> {
        const requestOptions = await this.askTutorRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TutorQuestionResponseFromJSON(jsonValue));
    }

    /**
     * Permite a un estudiante realizar una consulta académica. El Tutor IA genera una respuesta utilizando información contextual recuperada mediante RAG. 
     * Realizar una consulta al Tutor IA
     */
    async askTutor(requestParameters: AskTutorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TutorQuestionResponse> {
        const response = await this.askTutorRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
